### ISSUE TITLE
Parameter usability in 3.0.3

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/architecture-setup#11]
https://github.com/ICGC-TCGA-PanCancer/architecture-setup/blob/develop/roles/arch3_master/templates/deployer_params.j2
Currently, this gets the value "localhost" rather than the private IP address for the queue host

**Comment by SolomonShorser-OICR** [comment]
The arch3_master role is supposed to executed to set up the pancancer_launcher. so in this case, it's OK that queueHost is localhost because rabbitMQ is installed directly into the pancancer_launcher container.

**Comment by denis-yuen** [comment]
Sounds good
